version: "3"
services:
  app:
    build:
      context: .
    depends_on:
      - postgres
      - mongo
    restart: always
    env_file:
      - .env
    ports:
      - 5000:5000
  postgres:
    container_name: psql
    image: postgres:13
    restart: always
    env_file:
      - .env
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    ports:
      - 5433:5432
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    env_file:
      - .env
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - 8080:80
  mongo:
    container_name: mongodb
    image: mongo:bionic
    restart: always
    env_file:
      - .env
    volumes:
      - ./mongodata:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
    ports:
      - 27018:27017
volumes:
    mongo-data:
    pgadmin-data:
