enum AuthActions {
  SIGNUP_REQUEST = 'AUTH_SIGNUP_REQUEST',
  SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS',
  SIGNUP_FAILURE = 'AUTH_SIGNUP_FAILURE',

  SIGNIN_REQUEST = 'AUTH_SIGNIN_REQUEST',
  SIGNIN_SUCCESS = 'AUTH_SIGNIN_SUCCESS',
  SIGNIN_FAILURE = 'AUTH_SIGNIN_FAILURE',

  FETCH_REQUEST = 'AUTH_FETCH_REQUEST',
  FETCH_SUCCESS = 'AUTH_FETCH_SUCCESS',
  FETCH_FAILURE = 'AUTH_FETCH_FAILURE',

  LOGOUT = 'AUTH_LOGOUT',
}

export default AuthActions;
