export enum AuthActions {
  SIGNUP_REQUEST = 'AUTH/SIGNUP_REQUEST',
  SIGNUP_SUCCESS = 'AUTH/SIGNUP_SUCCESS',
  SIGNUP_FAILURE = 'AUTH/SIGNUP_FAILURE',

  SIGNIN_REQUEST = 'AUTH/SIGNIN_REQUEST',
  SIGNIN_SUCCESS = 'AUTH/SIGNIN_SUCCESS',
  SIGNIN_FAILURE = 'AUTH/SIGNIN_FAILURE',

  LOGOUT = 'AUTH/LOGOUT',
}
