export enum ForumActions {
  FETCH_TOPICS_REQUEST = 'FORUM/FETCH_TOPICS_REQUEST',
  FETCH_TOPICS_SUCCESS = 'FORUM/FETCH_TOPICS_SUCCESS',
  FETCH_TOPICS_FAILURE = 'FORUM/FETCH_TOPICS_FAILURE',

  ADD_TOPIC_REQUEST = 'FORUM/ADD_TOPIC_REQUEST',
  ADD_TOPIC_SUCCESS = 'FORUM/ADD_TOPIC_SUCCESS',
  ADD_TOPIC_FAILURE = 'FORUM/ADD_TOPIC_FAILURE',

  UPDATE_TOPIC_REQUEST = 'FORUM/UPDATE_TOPIC_REQUEST',
  UPDATE_TOPIC_SUCCESS = 'FORUM/UPDATE_TOPIC_SUCCESS',
  UPDATE_TOPIC_FAILURE = 'FORUM/UPDATE_TOPIC_FAILURE',
}
