export enum ForumActions {
  FETCH_TOPICS_REQUEST = 'FORUM/FETCH_TOPICS_REQUEST',
  FETCH_TOPICS_SUCCESS = 'FORUM/FETCH_TOPICS_SUCCESS',
  FETCH_TOPICS_FAILURE = 'FORUM/FETCH_TOPICS_FAILURE',

  FETCH_TOPIC_REQUEST = 'FORUM/FETCH_TOPIC_REQUEST',
  FETCH_TOPIC_SUCCESS = 'FORUM/FETCH_TOPIC_SUCCESS',
  FETCH_TOPIC_FAILURE = 'FORUM/FETCH_TOPIC_FAILURE',

  ADD_TOPIC_REQUEST = 'FORUM/ADD_TOPIC_REQUEST',
  ADD_TOPIC_SUCCESS = 'FORUM/ADD_TOPIC_SUCCESS',
  ADD_TOPIC_FAILURE = 'FORUM/ADD_TOPIC_FAILURE',

  UPDATE_TOPIC_REQUEST = 'FORUM/UPDATE_TOPIC_REQUEST',
  UPDATE_TOPIC_SUCCESS = 'FORUM/UPDATE_TOPIC_SUCCESS',
  UPDATE_TOPIC_FAILURE = 'FORUM/UPDATE_TOPIC_FAILURE',

  ADD_COMMENT_REQUEST = 'FORUM/ADD_COMMENT_REQUEST',
  ADD_COMMENT_SUCCESS = 'FORUM/ADD_COMMENT_SUCCESS',
  ADD_COMMENT_FAILURE = 'FORUM/ADD_COMMENT_FAILURE',
}
