export enum UserActions {
  FETCH_REQUEST = 'USER/FETCH_REQUEST',
  FETCH_SUCCESS = 'USER/FETCH_SUCCESS',
  FETCH_FAILURE = 'USER/FETCH_FAILURE',

  CHANGE_PROFILE_REQUEST = 'USER/CHANGE_PROFILE_REQUEST',
  CHANGE_PROFILE_SUCCESS = 'USER/CHANGE_PROFILE_SUCCESS',
  CHANGE_PROFILE_FAILURE = 'USER/CHANGE_PROFILE_FAILURE',

  CHANGE_AVATAR_REQUEST = 'USER/CHANGE_AVATAR_REQUEST',
  CHANGE_AVATAR_SUCCESS = 'USER/CHANGE_AVATAR_SUCCESS',
  CHANGE_AVATAR_FAILURE = 'USER/CHANGE_AVATAR_FAILURE',

  CHANGE_PASSWORD_REQUEST = 'USER/CHANGE_PASSWORD_REQUEST',
  CHANGE_PASSWORD_SUCCESS = 'USER/CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_FAILURE = 'USER/CHANGE_PASSWORD_FAILURE',
}
